In [15]:
import pandas as pd
import numpy as np
from copy import deepcopy

In [3]:
#label is a binary array with 1 and 0. findindex returns the index of kth
#nonzero item. k start from 1 and the returned index start from zero
def findindex(label,k):
    j=0
    for i,item in enumerate(label):
        if item != 0:
            j+=1
        if j==k:
            return(i)
    

In [13]:
#graph is a list with each element an array. The ith array contains the neighbor of the ith vertex.
#labels is used to label the vertex which are still active (1 for active 0 for not inactive) 
#v1 and v2 (start from zero v1 < v2) are the index of the selected two vetices about to fuse.
def fusion(graph, labels, v1, v2):
    #eliminate vertex v2
    labels[v2]=0
    
    #remove the slef loop
    if (v2) in graph[v1]:
        index1,=np.where(graph[v1]==v2)
        index2,=np.where(graph[v2]==v1)
        graph[v2]=np.delete(graph[v2],index2)
        graph[v1]=np.delete(graph[v1],index1)
    
    graph[v1]=np.concatenate([graph[v1],graph[v2]])
    
    #Since v2+1 is fused to v1 +1, we need to update all the v2+1 with v1+1
    for i in np.arange(len(label)):
        np.place(graph[i],graph[i]==v2, v1)
            
    
    

In [16]:
test=np.array([np.array([1,2,3]),np.array([0,3]),np.array([0,3]),np.array([0,1,2])])
label=np.array([1,1,1,1],dtype=np.int8)
test_cp=deepcopy(test)

fusion(test_cp,label,0,1)
print(test_cp)
print(label)
print(test)
#fusion(test, label,0,3)
#print(test)
#print(label)

[array([2, 3, 3]) array([3]) array([0, 3]) array([0, 0, 2])]
[1 0 1 1]
[array([1, 2, 3]) array([0, 3]) array([0, 3]) array([0, 1, 2])]


In [96]:
f=open('input',"r")
graph=f.readlines()
for i,item in enumerate(graph):
    graph[i]=np.asarray([int(x) for x in graph[i].strip().split('\t')])[1:]-1
f.close
n=len(graph)

#initial number of vetices
#initial_v=[lambda x: x for x in graph]
#initial_v

In [92]:
f=open('test3','r')
graph=f.readlines()
for i,item in enumerate(graph):
    graph[i]=np.asarray([int(x) for x in graph[i].strip().split(' ')])[1:]-1
f.close
n=len(graph)
graph

[array([18, 14, 35, 22, 17, 38]),
 array([35, 22,  3, 17, 25,  8]),
 array([34,  5, 15, 10]),
 array([22,  1, 17, 23]),
 array([13,  7, 28, 20]),
 array([33, 34,  2, 15]),
 array([29, 32, 37, 27]),
 array([11, 13,  4, 28, 30]),
 array([38, 12, 19,  9, 16,  1]),
 array([ 8, 19, 11, 13, 28]),
 array([ 2, 15, 29, 32, 25]),
 array([19,  9, 13,  7]),
 array([23, 38,  8, 19]),
 array([ 9, 11,  7,  4]),
 array([25, 18,  0, 35]),
 array([ 5,  2, 10, 29, 16, 34, 31]),
 array([37, 27, 31, 39,  8, 15]),
 array([ 1,  3, 23, 38,  0]),
 array([26, 25, 14,  0]),
 array([12,  8,  9, 11]),
 array([ 4, 28, 24, 36]),
 array([31, 39, 33, 34]),
 array([ 0, 35,  1,  3]),
 array([ 3, 17, 38, 12]),
 array([28, 20, 36, 30]),
 array([30, 26, 18, 14, 10,  1]),
 array([36, 30, 25, 18, 28]),
 array([ 6, 37, 16, 31]),
 array([ 7,  4, 20, 24,  9, 26]),
 array([15, 10, 32,  6, 36]),
 array([24, 36, 26, 25,  7]),
 array([27, 16, 39, 21, 15]),
 array([10, 29,  6, 37]),
 array([39, 21, 34,  5]),
 array([21, 33,  5,  2, 

In [100]:
mincut=[]

for s in np.arange(10000):
    #print('*'*10)
    n=len(graph)
    labels=np.ones(n, dtype=np.int8)
    graph1=deepcopy(graph)

    for i in np.arange(n-2):
    #randomly choose the first vertex
        k1=np.random.randint(0,n-i)
        v1=findindex(labels,k1+1)
        #print('v1:',v1)
        
    #randomly choose one of v1's neighbor
        index_v2=np.random.randint(0,len(graph1[v1]))
        v2=graph1[v1][index_v2]
        #print('v2:',v2)
        
    #make sure v1 is the smaller one 
        if v1>v2:
            v1, v2 = v2, v1

        #print(v1,v2)
        fusion(graph1,labels,v1,v2)
        #print(labels)
        #print(graph1)
        #print(graph)
    mincut.append(len(graph1[0]))


#mincut_eff=list(filter(lambda x: x>0, mincut))
print(min(mincut))
print(mincut)

24
[63, 524, 787, 492, 652, 821, 966, 158, 276, 823, 157, 495, 221, 874, 1075, 469, 211, 414, 217, 791, 950, 367, 827, 449, 979, 990, 985, 313, 177, 523, 131, 550, 526, 329, 570, 382, 213, 776, 355, 607, 975, 640, 254, 918, 646, 972, 911, 238, 708, 1024, 1136, 393, 880, 591, 462, 1021, 804, 396, 684, 683, 848, 441, 309, 783, 64, 441, 116, 392, 510, 252, 1158, 463, 304, 195, 247, 966, 600, 444, 733, 357, 856, 1144, 298, 228, 787, 598, 1118, 137, 549, 802, 443, 315, 809, 581, 283, 687, 893, 366, 155, 962, 769, 447, 188, 443, 610, 388, 369, 51, 823, 461, 612, 625, 1301, 780, 503, 686, 257, 428, 193, 422, 246, 771, 139, 295, 316, 1063, 630, 211, 1415, 845, 562, 344, 266, 659, 652, 332, 447, 111, 493, 430, 911, 704, 1021, 880, 726, 769, 855, 578, 113, 282, 200, 423, 901, 982, 379, 921, 821, 535, 928, 942, 349, 859, 1622, 352, 474, 521, 454, 1179, 410, 147, 656, 576, 415, 881, 1132, 304, 773, 227, 287, 588, 282, 948, 234, 473, 1272, 139, 489, 225, 557, 552, 223, 497, 452, 175, 852, 245, 351,